# .streamlit/secrets.toml
SUPABASE_URL = "https://ivhhzckkfofyvmbtbljx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aGh6Y2trZm9meXZtYnRibGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjkwMDMsImV4cCI6MjA3NDI0NTAwM30.HGw1yakVBdE5iyz8j8OR_AcViOUA1xFDMVVIqwZhHss"
GITHUB_RAW_URL = "https://raw.githubusercontent.com/cadyjko/slogan/main/slogans.xlsx"
